import test from 'node:test';
import assert from 'node:assert/strict';
import { initDetailDrawer } from '../public/js/ui/detail-drawer.js';

class MockElement {
  constructor(tagName = 'div', id = '') {
    this.tagName = tagName.toUpperCase();
    this.id = id;
    this.children = [];
    this.parentElement = null;
    this.attributes = {};
    this.listeners = {};
    this.hidden = true;
    this.focused = false;
    this._innerHTML = '';
  }

  setAttribute(name, value) {
    this.attributes[name] = String(value);
  }

  getAttribute(name) {
    return this.attributes[name];
  }

  focus() {
    this.focused = true;
  }

  addEventListener(type, fn) {
    if (!this.listeners[type]) this.listeners[type] = [];
    this.listeners[type].push(fn);
  }

  dispatchEvent(event) {
    const handlers = this.listeners[event.type] || [];
    for (const fn of handlers) {
      fn(event);
    }
  }

  click() {
    this.dispatchEvent({ type: 'click' });
  }

  get innerHTML() {
    return this._innerHTML;
  }

  set innerHTML(html) {
    this._innerHTML = html;
    this.children = [];
    if (!html) return;

    // Parse simple HTML structure generated by open(rec)
    if (html.includes('data-close')) {
      const closeBtn = new MockElement('button');
      closeBtn.attributes['data-close'] = '';
      this.children.push(closeBtn);
    }
  }

  querySelector(selector) {
    if (selector === '[data-close]') {
      return this.children.find(c => c.attributes['data-close'] !== undefined) || null;
    }
    return null;
  }

  contains(target) {
    if (target === this) return true;
    return this.children.includes(target);
  }
}

function setupMockDOM() {
  const drawer = new MockElement('aside', 'drawer');
  const docListeners = {};

  globalThis.document = {
    getElementById: (id) => {
      if (id === 'drawer') return drawer;
      return null;
    },
    createElement: (tagName) => new MockElement(tagName),
    addEventListener: (type, fn) => {
      if (!docListeners[type]) docListeners[type] = [];
      docListeners[type].push(fn);
    },
    dispatchEvent: (event) => {
      const handlers = docListeners[event.type] || [];
      for (const fn of handlers) {
        fn(event);
      }
    },
  };

  return { drawer, docListeners };
}

function makeRecord() {
  return {
    index: 42,
    request: {
      method: 'POST',
      url: 'https://example.com/api/test?foo=bar',
      headers: { Authorization: 'Bearer token123', 'Content-Type': 'application/json' },
      pathParams: { id: '123' },
      queryParams: { foo: 'bar' },
      body: { name: 'test' },
    },
    response: {
      status: 200,
      statusText: 'OK',
      headers: { 'content-type': 'application/json' },
      body: { result: 'success' },
      bodyText: '{"result":"success"}',
    },
    errorCode: null,
    durationMs: 45,
    errorMessage: null,
  };
}

test('initDetailDrawer open mo drawer va hien thi thong tin request', () => {
  const { drawer } = setupMockDOM();
  const detailDrawer = initDetailDrawer();

  const rec = makeRecord();
  detailDrawer.open(rec);

  assert.equal(drawer.hidden, false);
  assert.equal(drawer.getAttribute('aria-hidden'), 'false');
  assert.ok(drawer.innerHTML.includes('Request #42'));
  assert.ok(drawer.innerHTML.includes('POST · 200 OK'));
  assert.ok(drawer.innerHTML.includes('https://example.com/api/test?foo=bar'));
  assert.ok(drawer.innerHTML.includes('Authorization: Bearer token123'));
  assert.ok(drawer.innerHTML.includes('&quot;result&quot;: &quot;success&quot;'));

  const closeBtn = drawer.querySelector('[data-close]');
  assert.ok(closeBtn);
  assert.equal(closeBtn.focused, true);
});

test('detailDrawer close va nut data-close dong drawer', () => {
  const { drawer } = setupMockDOM();
  const detailDrawer = initDetailDrawer();

  detailDrawer.open(makeRecord());
  assert.equal(drawer.hidden, false);

  const closeBtn = drawer.querySelector('[data-close]');
  closeBtn.click();

  assert.equal(drawer.hidden, true);
  assert.equal(drawer.getAttribute('aria-hidden'), 'true');
  assert.equal(drawer.innerHTML, '');
});

test('Escape key dong drawer khi drawer dang mo', () => {
  const { drawer } = setupMockDOM();
  const detailDrawer = initDetailDrawer();

  detailDrawer.open(makeRecord());
  assert.equal(drawer.hidden, false);

  // Trigger Escape key
  globalThis.document.dispatchEvent({ type: 'keydown', key: 'Escape' });

  assert.equal(drawer.hidden, true);
  assert.equal(drawer.innerHTML, '');
});

test('Click outside dong drawer', () => {
  const { drawer } = setupMockDOM();
  const detailDrawer = initDetailDrawer();

  detailDrawer.open(makeRecord());
  assert.equal(drawer.hidden, false);

  const outsideElement = new MockElement('div');
  outsideElement.closest = () => null; // not clicking inside #result-table tbody tr

  globalThis.document.dispatchEvent({ type: 'click', target: outsideElement });

  assert.equal(drawer.hidden, true);
});

test('Click bên trong drawer khong dong drawer', () => {
  const { drawer } = setupMockDOM();
  const detailDrawer = initDetailDrawer();

  detailDrawer.open(makeRecord());
  assert.equal(drawer.hidden, false);

  const insideElement = new MockElement('div');
  insideElement.closest = () => null;
  drawer.children.push(insideElement); // mark insideElement inside drawer

  globalThis.document.dispatchEvent({ type: 'click', target: insideElement });

  assert.equal(drawer.hidden, false);
});
